### ISSUE TITLE
Expand beyond walls.

### ISSUE THREAD

**Issue by Maitlans** [Huskehhh/FakeBlock#15]
Can this concept of showing fake blocks be expanded beyond walls? For example you have a quest where you have to build your own kingdom and there's quests which you will slowly build sections of the castle. Also things like helping NPC's build their homes and other RPG type scenarios. This could be done via schematics. Please let me know if this is possible? Thank you.

**Comment by Huskehhh** [comment]
Hey mate. This is going to be possible in v2. You can follow the progress of that in this PR.

https://github.com/Huskehhh/FakeBlock/pull/14

Aiming to have it completed in the next week or so!

**Comment by Maitlans** [comment]
Ooh that's great news, I wish you the best! I have a question, will this system be based on if the player obtains the permission then the fake schematic is revealed?

**Comment by Huskehhh** [comment]
> Ooh that's great news, I wish you the best! I have a question, will this system be based on if the player obtains the permission then the fake schematic is revealed?

It'll actually be the inverse! So if you have the permission you will NOT see the fake blocks

**Comment by Maitlans** [comment]
For schematics and things other than walls I think the other way around makes more sense, since you wouldn't want the schematic to be visible right off the bat and rather when they go through the quest a command can be executed on them to give them the ability to then see the building or whatever they accomplished. Would you consider adding an option to do it reversed than you currently have? It's a little confusing I think when it comes to more complex things. Thank you.

**Comment by Huskehhh** [comment]
I understand your point, however this functionality is possible using the exact same method, ie: by removing a permission from a player the fake blocks will appear.

I will consider providing an inverse functionality once the initial version is finished as it will require rewriting some of the internals.

**Comment by Maitlans** [comment]
Thanks for considering, I think the issue is how do you give the player all these permissions when they join your server and if you add more hidden structures it would require for you to also give them those permissions to then later take them away, unless the plugin handles this automatically if not it's 2 steps for server owners to do rather than the 1 step of just giving the permission to make it appear. I appreciate the discussion. Can't wait to see the structures support :D

**Comment by Huskehhh** [comment]
This has been fixed in https://github.com/Huskehhh/FakeBlock/commit/9fc0306eb10605e011ad814e3a168b049ea180ad

**Comment by Huskehhh** [comment]
Just following up @Maitlans, would you be interested in testing one of the early versions for issues?
Let me know :) thanks!

**Comment by Maitlans** [comment]
> Just following up @Maitlans, would you be interested in testing one of the early versions for issues?
> Let me know :) thanks!

I am so sorry I didn't see this message.
