### ISSUE TITLE
Feature request: separate permissions to create and view walls

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#18]
Spigot 1.16.1
FakeBlock 2.0.0-b2

Permission `fakeblock.admin` is required to create walls.
Permission `fakeblock.admin` causes walls to be displayed.

So, one is required to give the permission to create a wall, then remove it to hide the wall.

Feature request: remove viewing wall from `fakeblock.admin` permission.
There is already a separate permission `fakeblock.<wallName>` to show/hide the wall.

**Comment by Huskehhh** [comment]
Implemented, thanks again for your contributions :)

**Comment by SlimeDog** [comment]
Thanks. Confirmed fixed in 2.0.0-b4
