### ISSUE TITLE
Suggestion: Have both new and old permissions mechanics

### ISSUE THREAD

**Issue by Maitlans** [Huskehhh/FakeBlock#20]
I know I'm who suggested to add the current in place functionality for the structures to appear but the old mechanic to make walls vanish when given permission is also very good and has many different use cases, I originally thought you were going to add the ability for both not remove the other one entirely.  From what I saw of your commit this seemed like a massive rewrite just to get it to function like this so making both I'm guessing may be too much of a hassle but I thought I'd still suggest it in case it wasn't. By the way keep up the awesome work!

**Comment by Huskehhh** [comment]
Hey! Yeah I totally get you. It's not hard at all to add, it should only be a few lines :)

I'll look at adding it in the next version!

**Comment by Maitlans** [comment]
Is there any place I can get the builds for the development version? And am I able to use both formats at the same time? LIke Can I have a structure assigned with show when you have permission and another structure hide when you have permission? Or can it only be one or the other? Thank you.

**Comment by Huskehhh** [comment]
Hey - sorry this was lingering for so long. I've now tested and pulled into the main branch. You can find the latest build here:
https://github.com/Huskehhh/FakeBlock/actions/runs/206778445

**Comment by Maitlans** [comment]
Thank you, keep up the amazing work!  Does "inverse-permission-check: false" work as a per FakeBlock defined locations? Or is it just in general for all the regions, like can I have a location called "Wall" use the if you're given the permission it vanishes and another location called "House" and have it appear when given the permission?

**Comment by Huskehhh** [comment]
> Thank you, keep up the amazing work! Does "inverse-permission-check: false" work as a per FakeBlock defined locations? Or is it just in general for all the locations, like can I have a location called "Wall" use the if you're given the permission it vanishes and another location called "House" and have it appear when given the permission?

Sorry I didn't completely answer your last message. It is a global setting. Potentially could make it individual in the future though 👍

**Comment by Maitlans** [comment]
No worries, thank you for clarifying and that would be amazing!
