### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by Maitlans** [Huskehhh/FakeBlock#24]
Server Version: Paper 1.16.3 #191
Plugin version: Latest On Spigot Website version
I'm guessing this is because I'm trying to use it on the latest paper? 
Error: https://pastebin.com/9cU6Y21C

**Comment by Huskehhh** [comment]
What version of FakeBlock are you using?

**Comment by Maitlans** [comment]
So whenever I get close to a structure the server pretty much stops responding in-game I'll be just there nothing will be loading and I can't type commands, but on the console commands and such work.

**Comment by Huskehhh** [comment]
Can you provide more info? 

- What version of ProtocolLib
- Are you using the FakeBlock version I previously linked?
- Link to the spark sample

Thanks!

**Comment by Maitlans** [comment]
The issue persists when I go near the fakeblock wall, and it's fine when I remove the plugin.
https://spark.lucko.me/#vVPulxlHUx

**Comment by Huskehhh** [comment]
I'll investigate further on Monday

**Comment by Huskehhh** [comment]
This issue is now fixed, there was a pretty major flaw in my 1.16.2+ multi block change packet protocollib conversion so thanks heaps for the report 👍
