### ISSUE TITLE
BetonQuest compatibility

### ISSUE THREAD

**Issue by Wolf2323** [Huskehhh/FakeBlock#25]
Hello,

i am the developer of BetonQuest(https://github.com/BetonQuest/BetonQuest) and we want to add your plugin as a compatibillity plugin to us. You can see the current state of this in that issue: https://github.com/BetonQuest/BetonQuest/issues/1262

Now i want to discuss here, if you can help us using our plugin with BetonQuest.

First of all this plugin works realy nice and perfect. Also the code is realy clean and structured. But you do not have a real API. And with that we have two problems.
1. We can't pass your own single blocks or a set of blocks(maybe schematics from WorldEdit) to your plugin.
2. It is not possible to define what player can see what schematic, exepting your permission solution. We want a list of players, where we can add and remove players that can see the schematic.

I hope you can maybe help us with that. If you do not have the time to help us we would also contemplate to make some PR to solve this, if you are fine with that.

**Comment by Huskehhh** [comment]
Hey there! 
Thanks for showing interest in FakeBlock, it would be really cool to see it paired with a powerful quest system!
I am totally all for adding whatever methods you need to provide the type of functionality you wish, I just need to ponder and consider what is the best solution for that while still retaining the current structure and functionality!

**Comment by Wolf2323** [comment]
is there any way we can communicate more direct? Maybe discord? I DC name: `Wolf2323 | Gabriel#0172`

**Comment by Huskehhh** [comment]
This has been resolved now. Should you have any questions feel free to either message me on Discord or create another issue!

**Comment by Wolf2323** [comment]
Thanks i still have to look, when i can implement this, i am a little bit distracted ;)
