### ISSUE TITLE
Block Place in FaceBlock Wall

### ISSUE THREAD

**Issue by Wolf2323** [Huskehhh/FakeBlock#26]
## Bug report

**Spigot version:** `git.Paper-378 (MC: 1.15.2)`

**FakeBlock version:** `2.0.2-SNAPSHOT-b29`

### Description:
After a block was placed into a FakeBlock and the block is broaken there is no FakeBlock anymore

### How to reproduce:
1. Create a FakeBlock Wall
2. Place a Block  inside.
3. Break that Block

Now you show see, that there is no FakeBlock anymore

**Comment by Huskehhh** [comment]
This should be fixed with that commit, however I will test sometime this week 👍
