### ISSUE TITLE
Fake walls not saving in 1.16.4

### ISSUE THREAD

**Issue by LenderSchlender** [Huskehhh/FakeBlock#31]
**FakeBlock version (including build number)**
2.0.2 b27

**ProtocolLib version**
4.5.1

**Spigot/Paper version**
1.16.4 #279

**Describe the bug**
When you create a wall,it doesnt save it, but still removes the blocks

**To Reproduce**
1. do /fb create test
2. Select two Corners
3. Look in the Config file, and dont find saved walls, just the config option

**Expected behavior**
I expected it to create an entry in the config file

**Comment by LenderSchlender** [comment]
fakeblock version 2.0.2 build 27

**Comment by Huskehhh** [comment]
Unable to replicate using the latest release available [here](https://github.com/Huskehhh/FakeBlock/releases)

Please update and try again.
