### ISSUE TITLE
LuckPerms 'unset' doesn't trigger wall refresh

### ISSUE THREAD

**Issue by Benjamin2077** [Huskehhh/FakeBlock#35]
Hai I have a problem when I use the FakeBlock-latest-2.0.2-SNAPSHOT-b29.jar plugin on PaperSpigot 1.16.4 #416
and I create a FakeBlock structure with /fb create Test, selecting 2 corners, it does not get saved into the config.

This is the error I get in the console

15.01 21:12:32 [Server] ERROR TaskChain Exception on pro.husk.fakeblock.objects.CommonMaterialWall$$Lambda$6661/1385755999: java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getSectionPositions()Lcom/comphenix/protocol/reflect/StructureModifier;
15.01 21:12:32 [Server] ERROR Current Action Index was: 2
15.01 21:12:32 [Server] WARN java.lang.Exception: java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getSectionPositions()Lcom/comphenix/protocol/reflect/StructureModifier;
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.taskchain.TaskChain.handleError(TaskChain.java:1203)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.taskchain.TaskChain.access$600(TaskChain.java:57)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1320)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
15.01 21:12:32 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
15.01 21:12:32 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15.01 21:12:32 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15.01 21:12:32 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15.01 21:12:32 [Server] WARN at java.lang.Thread.run(Thread.java:748)
15.01 21:12:32 [Server] WARN Caused by: java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getSectionPositions()Lcom/comphenix/protocol/reflect/StructureModifier;
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.objects.MultiBlockChange.build(MultiBlockChange.java:63)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.objects.LatestMaterialWall.lambda$buildPacketList$0(LatestMaterialWall.java:62)
15.01 21:12:32 [Server] WARN at java.util.HashMap$Values.forEach(HashMap.java:981)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.objects.LatestMaterialWall.buildPacketList(LatestMaterialWall.java:61)
15.01 21:12:32 [Server] WARN at
pro.husk.fakeblock.objects.CommonMaterialWall.lambda$new$1(CommonMaterialWall.java:54)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
15.01 21:12:32 [Server] WARN at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
15.01 21:12:32 [Server] WARN ... 7 more

Is this a problem on my end or with the spigot 1.16.4 compatibility?

Kind regards!

**Comment by Huskehhh** [comment]
Looks like you need the latest protocollib

available here:
https://ci.dmulloy2.net/job/ProtocolLib/492/

**Comment by Benjamin2077** [comment]
Oh thank you very much for the fast response! yes that dit work!

Then I have only one more question but I don't know if that is a Minecraft limitation or something but when I add the permission FakeBlock.<wall> it within seconds the structure appears. But when I delete the permission the structure stays until I leave the server (or right click on all block so they disappear)

Is this something that I can fix or is this just a limitation?

**Comment by Huskehhh** [comment]
> 
> 
> Oh thank you very much for the fast response! yes that dit work!
> 
> Then I have only one more question but I don't know if that is a Minecraft limitation or something but when I add the permission FakeBlock. it within seconds the structure appears. But when I delete the permission the structure stays until I leave the server (or right click on all block so they disappear)
> 
> Is this something that I can fix or is this just a limitation?

This shouldn't be the case at all, it's *meant* to hide the structure when permission is removed. I'll look into it!

**Comment by Huskehhh** [comment]
Am unable to replicate. It's working fine for me.

Are you using LuckPerms? If so, make sure it's up to date!

**Comment by Benjamin2077** [comment]
Yes I use LuckyPerms just download the newest version but I still have that problem.
I filmed the problem and put it in YouTube (because the file was to big)

https://youtu.be/RAzRl_2IaE8

**Comment by Huskehhh** [comment]
> 
> 
> Yes I use LuckyPerms just download the newest version but I still have that problem.
> I filmed the problem and put it in YouTube (because the file was to big)
> 
> [youtu.be/RAzRl_2IaE8](https://youtu.be/RAzRl_2IaE8)

Interesting. I only can replicate this when using LuckPerms 'unset' permission command. I'll investigate further!

**Comment by Huskehhh** [comment]
This actually does work - the reason it was not showing when using the unset command was that it was still allowing it to be overridden by either wildcard (*) or OP permission. This can be validated through checking
``/lp user <user> permission check fakeblock.wallname``, it will tell you the source of where the node is being inherited from.
If you want to negate the node regardless of inheritance, the method to do that would be to use the set equivalent:
``/lp user <user> permission set fakeblock.wallname false`` which does the same, however explicitly removes that permission from the user (regardless of wildcard/op)

This ticket is now resolved
