### ISSUE TITLE
fake blocks disappear after being punched

### ISSUE THREAD

**Issue by Yriokiri** [Huskehhh/FakeBlock#36]
hi, i was trying you're plugin FakeBlocks but when i tried to punch a block, (just punching it and not breaking it) it disappeared, and it will reapper only when trowning another punch on another block . and when walking on the blocks i get kicked for flying.

here is a video about the thing im talking about https://www.youtube.com/watch?v=JD3GmtIf0dk

**Comment by Huskehhh** [comment]
I need some more info on this please!

What version FakeBlock:
What version ProtocolLib:
What version of server software:
Latency to server:

**Comment by Yriokiri** [comment]
What version FakeBlock: **FakeBlock-latest-2.0.2-SNAPSHOT-b29**
What version ProtocolLib:  **4.6.0**
What version of server software:    **paper 1.16.5-587**
Latency to server: **29ms**

**Comment by Huskehhh** [comment]
Fixed in https://github.com/Huskehhh/FakeBlock/commit/6d5251c65e60f495e128f9c9d8a572b3a52443af

Thanks for the report!

**Comment by Yriokiri** [comment]
hey, i saw that you fixed the issue, to download the fix i need to wait the new update? if yes there is an ETA for that? or is there a dev build section?    Il sabato 17 aprile 2021, 02:23:39 CEST, Jordyn Newnham ***@***.***> ha scritto:  
 
 


Closed #36.

**Comment by Huskehhh** [comment]
> hey, i saw that you fixed the issue, to download the fix i need to wait the new update? if yes there is an ETA for that? or is there a dev build section? Il sabato 17 aprile 2021, 02:23:39 CEST, Jordyn Newnham ***@***.***> ha scritto: Closed #36. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hey, you can now find bleeding edge builds over on the actions page: latest as of this post is
https://github.com/Huskehhh/FakeBlock/actions/runs/760444668

**Comment by Yriokiri** [comment]
another question. Is possible to select air as a position for the fake blocks area? because now i can only create a selection clicking on 2 blocks but i would like to make a selection like this and the upper angle of the position is air

    Il domenica 18 aprile 2021, 11:37:52 CEST, Jordyn Newnham ***@***.***> ha scritto:  
 
 



hey, i saw that you fixed the issue, to download the fix i need to wait the new update? if yes there is an ETA for that? or is there a dev build section? Il sabato 17 aprile 2021, 02:23:39 CEST, Jordyn Newnham @.***> ha scritto: Closed #36. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Hey, you can now find bleeding edge builds over on the actions page: latest as of this post is
https://github.com/Huskehhh/FakeBlock/actions/runs/760444668
