### ISSUE TITLE
Improve area selection

### ISSUE THREAD

**Issue by Yriokiri** [Huskehhh/FakeBlock#39]
possibility to select air as a position for the fake blocks area. Because right now i can only select an area placing 2 blocks like this

![Screenshot_606](https://user-images.githubusercontent.com/77204889/116860741-51f73680-ac02-11eb-8ad8-4eaf85c3ef85.png)

**Comment by Huskehhh** [comment]
> possibility to select air as a position for the fake blocks area. Because right now i can only select an area placing 2 blocks like this
> 
> ![Screenshot_606](https://user-images.githubusercontent.com/77204889/116860741-51f73680-ac02-11eb-8ad8-4eaf85c3ef85.png)

This is a limitation of the game - you cannot click an "air block".
Perhaps it would be better for me to interface with WorldEdit and utilise their selection capabilities.

**Comment by Yriokiri** [comment]
bdw do you have an eta for the update? so i know if i can wait to set it up or not

**Comment by Huskehhh** [comment]
> bdw do you have an eta for the update? so i know if i can wait to set it up or not

No ETA unfortunately. I only work on this project when I have the spare time and interest. You can track the progress of the update on this page https://github.com/Huskehhh/FakeBlock/projects/1#card-60395895

**Comment by Huskehhh** [comment]
This is complete via the mentioned commit.

``language.yml`` will need to be regenerated for this to work

Bleeding edge build is available at: https://github.com/Huskehhh/FakeBlock/actions
However no testing has been done on this build, use at your own risk!
