### ISSUE TITLE
Feature request: Message formats and localization

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#7]
Please provide configuration options to remove formatting codes from all messages sent to game and console. Alternatively, a language file, which would also provide localization opportunities. Note that PREFIX should be configurable, as well as message content. For example:

[21:18:18] [Server thread/INFO]: ^[[0;30;22m[^[[0;36;1mFakeBlock^[[0;30;22m] ^[[0;31;1m'xyzzy' has been deleted^[[m

prefix: cyan/aqua
message: red

**Comment by Huskehhh** [comment]
Roger that. Another decent idea. I'll look into adding this into the next version :)

**Comment by SlimeDog** [comment]
Is there a testable version?

**Comment by SlimeDog** [comment]
Tested:
- **fb reload** should reload the language file.

**Comment by SlimeDog** [comment]
... and it should log that it was reloaded.
```
>fb reload
[22:18:22] [Server thread/INFO]: [FakeBlock] Walls reloaded
```
should be something like
```
>fb reload
[22:18:22] [Server thread/INFO]: [FakeBlock] Walls and language reloaded
```

**Comment by Huskehhh** [comment]
Updated the default message in the language file to reflect.
