### ISSUE TITLE
Feature request: Visualization command

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#8]
Please consider a command to temporarily display local walls, or a specific (named) wall, to an otherwise privileged player. A toggle is probably best.

**Comment by Huskehhh** [comment]
Awesome idea. Thanks heaps! I'll add this shortly.

**Comment by SlimeDog** [comment]
Is there a testable version?

**Comment by Huskehhh** [comment]
[Sure is!](https://husk.pro/dl/FakeBlock-latest-1.7-SNAPSHOT.jar)

**Comment by SlimeDog** [comment]
I guess I miscalculated the timing. Build 33 has this (and #7)?

**Comment by Huskehhh** [comment]
No sir, as it was in another branch, the CI server wouldn't have generated a build yet. Not until the pull request is finalised 👍

**Comment by SlimeDog** [comment]
I am confused? Is there a publicly-available test version that includes #7 and #8 ?

**Comment by Huskehhh** [comment]
> 
> 
> I am confused. Is there a publicly-available test version that includes #7 and #8 ? If yes, please provide a link to it. :)



> 
> 
> [Sure is!](https://husk.pro/dl/FakeBlock-latest-1.7-SNAPSHOT.jar)
Might have been hard to see, I attached the link to this reply.
https://husk.pro/dl/FakeBlock-latest-1.7-SNAPSHOT.jar

**Comment by SlimeDog** [comment]
OK, I've tested it. I'm not sure what is expected (it's not documented yet), but
- The player parameter should be optional, defaulting to the invoker if executed by a player (with permission).
- "toggle" implies that it toggles on and off. I can get it to toggle on, but not off. Disconnect/reconnect verifies that it is off (unless it is always off on reconnect).
- Execution from the console (or in-game) should report if the target player is offline. Toggle is not persistent (not stored anywhere), so it cannot apply to an offline player.

**Comment by SlimeDog** [comment]
There would be a lot more testing if you posted them as dev builds. No one (except you and me) knows about these hidden downloads.
